/**
 * Centralized Google reCAPTCHA v3 Server-Side Verification Utility
 */

export interface RecaptchaVerificationResult {
  success: boolean;
  score?: number;
  action?: string;
  error?: string;
  bypassed?: boolean;
}

/**
 * Verifies a Google reCAPTCHA v3 token server-side using Google's Site Verify API.
 * 
 * @param token - The reCAPTCHA v3 token generated by the client
 * @param expectedAction - Optional expected action name (e.g. 'public_enquiry_submit', 'user_login')
 * @param scoreThreshold - Configurable minimum score threshold (default: 0.5)
 */
export async function verifyRecaptchaToken(
  token: string | null | undefined,
  expectedAction?: string,
  scoreThreshold: number = 0.5
): Promise<RecaptchaVerificationResult> {
  const secretKey = process.env.RECAPTCHA_SECRET_KEY;

  // Development / Unconfigured Mode Fallback
  if (!secretKey || secretKey.trim() === "" || secretKey.includes("YOUR_RECAPTCHA")) {
    console.warn(
      "[reCAPTCHA Warning] RECAPTCHA_SECRET_KEY is missing or unconfigured in environment. Bypassing verification for development."
    );
    return {
      success: true,
      score: 1.0,
      bypassed: true,
    };
  }

  if (!token || typeof token !== "string" || token.trim() === "") {
    console.error("[reCAPTCHA Failed] Verification failed: Missing or empty token provided.");
    return {
      success: false,
      score: 0,
      error: "Missing reCAPTCHA verification token.",
    };
  }

  try {
    const verifyUrl = "https://www.google.com/recaptcha/api/siteverify";
    const bodyParams = new URLSearchParams({
      secret: secretKey,
      response: token,
    });

    const response = await fetch(verifyUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: bodyParams.toString(),
    });

    const data = await response.json();

    if (!data.success) {
      const errorCodes = Array.isArray(data["error-codes"]) ? data["error-codes"].join(", ") : "Unknown error";
      console.error(`[reCAPTCHA Failed] Google Site Verify API error. Error codes: ${errorCodes}`);
      return {
        success: false,
        score: 0,
        error: `reCAPTCHA verification failed: ${errorCodes}`,
      };
    }

    const score = typeof data.score === "number" ? data.score : 1.0;
    const action = data.action || "";

    // Action mismatch check
    if (expectedAction && action && action.toLowerCase() !== expectedAction.toLowerCase()) {
      console.error(
        `[reCAPTCHA Failed] Action mismatch! Expected: '${expectedAction}', Got: '${action}'. Score: ${score}`
      );
      return {
        success: false,
        score,
        action,
        error: `reCAPTCHA action mismatch. Expected ${expectedAction}, got ${action}.`,
      };
    }

    // Score threshold check
    if (score < scoreThreshold) {
      console.error(
        `[reCAPTCHA Low Score Blocked] Low trust score detected (${score}). Threshold required: ${scoreThreshold}. Action: ${action}`
      );
      return {
        success: false,
        score,
        action,
        error: `Suspicious activity detected (Trust score: ${score}). Request blocked.`,
      };
    }

    // Clean verification success
    return {
      success: true,
      score,
      action,
    };
  } catch (error: any) {
    console.error("[reCAPTCHA Error] Error communicating with Google Site Verify API:", error);
    return {
      success: false,
      score: 0,
      error: "Failed to communicate with reCAPTCHA verification service.",
    };
  }
}
